name: Chocolatine

on:
    push:
        branches-ignore:
            - "ga-ignore-*"
    pull_request:
        branches-ignore:
            - "ga-ignore-*"

env:
    MIRROR_URL: git@github.com/EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-julia.tran
    EXECUTABLES: "test"
    
jobs:
    check_repository_cleanliness:
        name: check clean
        runs-on: unbuntu-latest
        steps:
          - name: Check repository
            uses: action/checkout@v2
            with:
                fetch-depth: 0
    check_program_compilation:
        name: check compilation
        runs-on: unbuntu-latest
        container: epitechcontent/epitest-docker
        needs:
            - check_repository_cleanliness
        steps:        
          - name: Check repository
            uses: action/checkout@v2
            with:
                fetch-depth: 0
          - name: Compilation execution     
            timeout_minutes: 2
            run: make
          - name: Compilation clean  
            timeout_minutes: 2
            run: make clean
    run_tests:
        name: check test
        runs-on: unbuntu-latest
        container: epitechcontent/epitest-docker
        needs:
            - check_program_compilation
        steps:
          - name: Check repository
            uses: action/checkout@v2
            with:
                fetch-depth: 0
          - name: Compilation test
            timeout_minutes: 2
            run: make tests_run
    push_to_mirror:
        name: Mirorring                         
        runs-on: ubuntu-latest
        needs:
            - run_tests 
        steps:
          - name: Check repository
            uses: actions/checkout@v2
            with:
                fetch-depth: 0
          - name: Check mirorring
            uses: pixta-dev/repository-mirroring-action@v1
            with:
                target_repo_url:
                    ${{ env.MIRROR_URL }}
                ssh_private_key:
                    ${{ secrets.GIT_SSH_PRIVATE_KEY }}
      